spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shopping_db
    username: postgres
    password: 3232
    initialization-mode: always
  logging:
    level:
      org.springframework: DEBUG

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      javax:
        persistence:
          validation:
            mode: none

shopping:
  app:
    jwtSecret: SecretKey
    jwtExpirationMs: 86400000